### ISSUE TITLE
install troubles

### ISSUE THREAD

**Issue by BMaxV** [CodeCreatePlay360/PandaEditor#2]
Hey there,

cool project, having a few troubles getting it to run, so I'm writing this issue for help and documentation.

the wxPython install didn't work so I searched a bit and install a wheel from : https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/ 

This one

 wxPython-4.1.1-cp38-cp38-linux_x86_64.whl

installed something but when I try to run it, I get this error.

```
  File "/home/user/.local/lib/python3.8/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
```

Also the main.py doesn't do it's path stuff correctly, so it can't import from editor as intended.
```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from editor.app import MyApp
ModuleNotFoundError: No module named 'editor'
```

**Comment by CodeCreatePlay360** [comment]
Hi, the issue with the paths is now resolved with the latest update, as for wxPython wheels you should download an appropriate wheel from here https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/ . 

If you still face any install issues, feel free to open a new issue on GitHub or hit the discord, thanks.
