### ISSUE TITLE
Application is unable to load resources due to wrong path conversion

### ISSUE THREAD

**Issue by kergalym** [CodeCreatePlay360/PandaEditor#4]
Hi,

After I start application inside virtualenv via command `python3.9 main.py ` I get following error leading to that the application stops working:
![изображение](https://user-images.githubusercontent.com/9489149/227743491-32d97923-71ae-497c-aff2-bc31f226d4d2.png)

It seems, application needs correct path conversion for Unix systems and Windows, which has been covered in the [Panda3D manual](https://docs.panda3d.org/1.10/python/programming/advanced-loading/filename-syntax)

**Comment by CodeCreatePlay360** [comment]
Hi, the issue with paths is now resolved with the latest update, as for wxPython wheels you should download an appropriate wheel from here https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/ .

Please go ahead and give it a test, if you still face any install issues, feel free to open a new issue on GitHub or hit the discord, thanks.
