### ISSUE TITLE
Does PandaEditor support collisions?

### ISSUE THREAD

**Issue by Legopapurida** [CodeCreatePlay360/PandaEditor#5]
Hello
Thanks for your awesome project
I have a question
can we add or manipulate collisions and add every type of collision to the object?

**Comment by CodeCreatePlay360** [comment]
As far as I understand from your question you want to create and manipulate collision solids through the editor UI / object manipulation gizmos, then it is currently not supported but definitely planned for future, as for now you will have to add collision through the code.
